<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * proctoringpolicy_evidence.php
 *
 * @package   proctoringpolicy_evidence
 * @copyright 2026 Eduardo Kraus {@link https://eduardokraus.com}
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die;

$string['allowdownload_cm'] = 'Allow evidence download in this exam';
$string['allowdownload_default'] = 'Allow download of evidence (teachers)';
$string['allowdownload_default_desc'] = 'If enabled, users with capability to review attempts can download evidence files.';
$string['cleanup_task_name'] = 'Kopere Proctoring evidence cleanup';
$string['enabled'] = 'Enable evidence management';
$string['enabled_cm'] = 'Enable evidence for this exam';
$string['enabled_desc'] = 'If enabled, evidence (webcam images, screenshots and other artifacts) will be managed and stored according to the rules below.';
$string['event_evidence_deleted'] = 'Evidence deleted by retention rules';
$string['event_evidence_stored'] = 'Evidence stored';
$string['heading'] = 'Evidence ';
$string['heading_info'] = 'Controls the lifecycle of proctoring evidence generated by the attempt, such as screenshots, webcam captures, and related artifacts. The policy defines retention time, maximum files per attempt, and reviewer download permissions.';
$string['legend'] = 'Evidence settings';
$string['log_cleanup'] = 'Evidence cleanup executed: coursemodule={$a->cmid}, attempt={$a->attemptid}';
$string['maxfiles_cm'] = 'Max evidence files per attempt (this exam)';
$string['maxfiles_cm_help'] = 'Maximum number of evidence files that will be kept for each attempt. Extra files may be discarded or cleaned up based on this limit.';
$string['maxfiles_default'] = 'Default max evidence files per attempt';
$string['maxfiles_default_desc'] = 'Maximum number of evidence files (webcam shots, screenshots, etc.) that will be kept per attempt. Use 0 for no limit.';
$string['pluginname'] = 'Evidence ';
$string['retention_cm'] = 'Retention (days) for this exam';
$string['retention_cm_help'] = 'Number of days that evidence will be kept after the attempt is finished. Use 0 to keep forever.';
$string['retention_default'] = 'Default retention (days)';
$string['retention_default_desc'] = 'Number of days that evidence should be kept before being removed. Use 0 to keep forever.';
$string['teacher_info'] = 'Use this policy to retain visual evidence for later audit. Set how long the files are stored, how many files can be kept per attempt, and whether reviewers may download the stored evidence.';
